cmake_minimum_required(VERSION 3.8)
project(tactile_robot_description)
find_package(ament_cmake REQUIRED)
install(DIRECTORY urdf launch rviz config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(combined_model test/test_model.py)
endif()
ament_package()
