/**:
  ros__parameters:
    rate: 30
    use_mimic_tags: true
    zeros:
      joint1: 0.0
      joint2: -0.6
      joint3: -0.8
      joint4: 0.0
      joint5: 1.4
      joint6: 0.0
      ag95_left_outer_knuckle_joint: 0.0
